server:
  port: 8080

spring:
  application:
    name: raiji

  datasource:
    url: jdbc:postgresql://localhost:5432/raiji_app
    username: raiji
    password: raiji123
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/raiji/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health

raiji:
  keycloak:
    base-url: http://localhost:8180
    realm: raiji
    admin-client-id: raiji-admin
    admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:raiji-admin-secret}
